# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-14 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO genre (genre) VALUES ('drama');"),
        migrations.RunSQL("INSERT INTO genre (genre) VALUES ('romance');"),
        migrations.RunSQL("INSERT INTO genre (genre) VALUES ('mystery');"),
        migrations.RunSQL("INSERT INTO genre (genre) VALUES ('history');"),
        migrations.RunSQL("INSERT INTO genre (genre) VALUES ('science fiction');")
    ]
